setwd(Frans-Framework)
load("fish_data.Rdata")
head(fish)
tapply(fish$parcel.density.m3, fish$transect.id, mean)
ParcelMean <- tapply(fish$parcel.density.m3, fish$transect.id, mean)
ParcelMean.df = as.data.frame(ParcelMean)
data.frame(ParcelMean)
Transect = rownames(ParcelMean)
ParcelMean = data.frame(Transect,ParcelMean)

tapply(fish$parcel.density.m3, fish$transect.id, sd)
ParcelDeviation <- tapply(fish$parcel.density.m3, fish$transect.id, sd)
ParcelDeviation.df = as.data.frame(ParcelDeviation)
data.frame(ParcelDeviation)
Transect = rownames(ParcelDeviation)
ParcelDeviation = data.frame(Transect,ParcelDeviation)

Merge1 = merge.data.frame(ParcelMean,ParcelDeviation, by = "Transect")

tapply(fish$parcel.density.m3, fish$transect.id,FUN = length)
ParcelCount <- tapply(fish$parcel.density.m3, fish$transect.id, FUN = length)
ParcelCount.df = as.data.frame(ParcelCount)
data.frame(ParcelCount)
Transect = rownames(ParcelCount)
ParcelCount = data.frame(Transect,ParcelCount)
Merge1 = merge.data.frame(Merge1,ParcelCount, by = "Transect")
head(Merge1)

library(dplyr)
load("fish_data.Rdata")
head(fish)
X = f%>%group_by(transect.id)%>%summarise(mean = mean(parcel.density.m3))
Xdf = as.data.frame(X)
data.frame(Xdf)
Transect = rownames(Xdf)
Xdf = data.frame(Transect,Xdf)
y = f%>%group_by(transect.id)%>%summarise(sd = sd(parcel.density.m3))
str(y)
head(y)
Ydf = as.data.frame(y)
data.frame(Ydf)
Join1 <- f%>% full_join(Xdf,Ydf, by = c(Transect))

tapply(fish$parcel.density.m3, fish$transect.id,FUN = length)
ParcelCount <- tapply(fish$parcel.density.m3, fish$transect.id, FUN = length)
ParcelCount.df = as.data.frame(ParcelCount)
data.frame(ParcelCount)
Transect = rownames(ParcelCount)
ParcelCount = data.frame(Transect,ParcelCount)
Join2 <- f%>% full_join(Join1,ParcelCount, by = c(Transect))


library(dplyr)
load("fish_data.Rdata")
head(fish)
ParcelLength = f%>%group_by(transect.id)%>%summarise(mean = mean(parcel.length.m))
ParcelLengthMean = data.frame(Transect, ParcelLength)
data.frame(ParcelLengthMean)
Transect = rownames(ParcelLengthMean)
ParcelLengthSD = f%>%group_by(transect.id)%>%summarise(sd = sd(parcel.length.m))
ParcelLengthSD = as.data.frame(ParcelLengthSD)
ParcelLengthSD = data.frame(Transect, ParcelLengthSD)
Merge1 = merge.data.frame(ParcelLengthMean,ParcelLengthSD, by = "Transect")
tapply(fish$parcel.length.m, fish$transect.id,FUN = length)
ParcelCount <- tapply(fish$parcel.length.m, fish$transect.id, FUN = length)
ParcelCount.df = as.data.frame(ParcelCount)
data.frame(ParcelCount)
Transect = rownames(ParcelCount)
ParcelCount = data.frame(Transect,ParcelCount)
Merge1 = merge.data.frame(Merge1,ParcelCount, by = "Transect")
head(Merge1)

ParcelLength = f%>%group_by(transect.id)%>%summarise(mean = mean(parcel.length.m))
head(ParcelLength)
mean(ParcelLength)
median(ParcelLength)
range(ParcelLengthMean)
max(ParcelLengthMean)
min(ParcelLengthMean)
quantile(ParcelLengthMean, probs = c(0.005, 0.0975))
